### ISSUE TITLE
Helmet noCache has been removed 

### ISSUE THREAD

**Issue by qasimalbaqali** [gkouziik/eslint-plugin-security-node#52]
The Helmet noCache `helmet.noCache` has been removed as a functionality from the helmet package in august https://github.com/helmetjs/helmet/blob/d491d281eb1cc55380046532d24fbc314af836e0/CHANGELOG.md#400---2020-08-02 and this is the issue that is related to the removal reason https://github.com/helmetjs/helmet/issues/215

A suggestion would be to also remove it as a rule. If you don't mind I can create a PR for this.

**Comment by gkouziik** [comment]
Thanks for the info, sure you can create a PL request for that, if you dont mind

**Comment by qasimalbaqali** [comment]
@gkouziik Thanks for the reply. I have created the PR accordingly #53

**Comment by gkouziik** [comment]
New version on NPM
