### ISSUE TITLE
Missing 'detect-helmet-without-nocache' in 1.0.13

### ISSUE THREAD

**Issue by briandiephuis** [gkouziik/eslint-plugin-security-node#55]
It seems that since  the 'detect-helmet-without-nocache' rule has been removed, but it is still present in the rules config and in the recommended rules causing our builds to fail;

```
'Failed to load plugin 'security-node' declared in '.eslintrc.json': Cannot find module './lib/rules/detect-helmet-without-nocache'
```

**Comment by briandiephuis** [comment]
Seems to be fixable by: https://github.com/gkouziik/eslint-plugin-security-node/pull/54

**Comment by gkouziik** [comment]
Ohh, im sorry, ill fix it right now!

**Comment by gkouziik** [comment]
Ok i fixed the refs in index.js file and published to npm!
