### ISSUE TITLE
detect-crlf false positive on any backtick string

### ISSUE THREAD

**Issue by UziTech** [gkouziik/eslint-plugin-security-node#56]
The following code should not cause `detect-crlf`

```js
console.log(`test`);
```

**Comment by gkouziik** [comment]
This rule will be deprecated. 
"eslint:recommended" already  contains that rule!

**Comment by UziTech** [comment]
What eslint rule prevents log injection?

**Comment by gkouziik** [comment]
Actually no console rule doesnt prevent possible log injection, you re right, it prevents console all the way :)
I have my doubts about this particular rule (log-injection)
That's why i didnt include this rule in the default configuration
I will fix the false positive case with backtick.

**Comment by exneval** [comment]
@gkouziik can't wait for the patch fix with backtick

**Comment by gkouziik** [comment]
@exneval  @UziTech 
I apologize. I will publish the version with the fix in weekend!!

**Comment by Efraa** [comment]
...

**Comment by gkouziik** [comment]
@UziTech @efraa  Can i close this issue ? 
I think with last update this issue has been solved
